meuDf <- read.table("C:\\Users\\danie\\Desktop\\DataSet.csv", header = TRUE,sep = ",")
fit <- lm(totalProblemasClasseFrequente ~ numeroCommits+linguagensProgramacaoUtilizadas+usoTestesAutomatizados+frequenciaInteracaoCliente+tamanhoSprints+artefatosEntreguesCiclo+ferramentasComunicacaoEquipe+tamanhoEquipe+periodoTisRealizado, data=meuDf)
fit2 <- lm(totalProblemas ~ numeroCommits+linguagensProgramacaoUtilizadas+usoTestesAutomatizados+frequenciaInteracaoCliente+tamanhoSprints+artefatosEntreguesCiclo+ferramentasComunicacaoEquipe+tamanhoEquipe+periodoTisRealizado, data=meuDf)
fit3 <- lm(totalProblemasErros ~ numeroCommits+linguagensProgramacaoUtilizadas+usoTestesAutomatizados+frequenciaInteracaoCliente+tamanhoSprints+artefatosEntreguesCiclo+ferramentasComunicacaoEquipe+tamanhoEquipe+periodoTisRealizado, data=meuDf)
fit4 <- lm(totalProblemasWarnings ~ numeroCommits+linguagensProgramacaoUtilizadas+usoTestesAutomatizados+frequenciaInteracaoCliente+tamanhoSprints+artefatosEntreguesCiclo+ferramentasComunicacaoEquipe+tamanhoEquipe+periodoTisRealizado, data=meuDf)
fit5 <- lm(totalClasses ~ numeroCommits+linguagensProgramacaoUtilizadas+usoTestesAutomatizados+frequenciaInteracaoCliente+tamanhoSprints+artefatosEntreguesCiclo+ferramentasComunicacaoEquipe+tamanhoEquipe+periodoTisRealizado, data=meuDf)
summary(fit)
summary(fit2)
summary(fit3)
summary(fit4)
summary(fit5)